github_analytics:
  outputs:
    dev:
      dataset: reddit_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: reddit-analytic-pipeline
      threads: 4
      type: bigquery
  target: dev
